function [ nuc_sum, feature] = ...
    cluster_sim( params_index , gene_index, sequences_structure, wt_3h)

% load all the necessary data:
addpath(genpath('/cs/bd/Daniel/nflab_scripts'));
addpath(genpath('/cs/bd/Daniel/nuc_simulator'));
seq = sequences_structure(gene_index,:);
wt_data = wt_3h(gene_index,:); 

% create the full parameter matrix
create_full_params;

% choose this specific sim parameters:
sim_params = params(: , params_index);

% the combvec params:
% combvec(poly_rates, tf_rates, tf_evic_eff, rsc_length, rsc_evic, rsc_slide)

% create five simulations that will be combined:
nuc_sum1 = run_simulation_from_genome(seq,'report',0, ...
	'poly_rate',sim_params(1), ...
	'REB1_a_rate', sim_params(2), 'REB1_e_rate', (sim_params(2)/2), ...
	'ABF1_a_rate', sim_params(2), 'ABF1_e_rate', (sim_params(2)/2), ...
	'RAP1_a_rate', sim_params(2), 'RAP1_e_rate', (sim_params(2)/2), ...
	'TF_evic_intensity', sim_params(3), ...
	'RSC_evic_length', sim_params(4), 'RSC_slide_length', sim_params(4).*2, ...
    'RSC_evic_intensity', sim_params(5), ...
	'RSC_slide_intensity', sim_params(6));
nuc_sum2 = run_simulation_from_genome(seq,'report',0, ...
	'poly_rate',sim_params(1), ...
	'REB1_a_rate', sim_params(2), 'REB1_e_rate', (sim_params(2)/2), ...
	'ABF1_a_rate', sim_params(2), 'ABF1_e_rate', (sim_params(2)/2), ...
	'RAP1_a_rate', sim_params(2), 'RAP1_e_rate', (sim_params(2)/2), ...
	'TF_evic_intensity', sim_params(3), ...
	'RSC_evic_length', sim_params(4), 'RSC_slide_length', sim_params(4).*2, ...
    'RSC_evic_intensity', sim_params(5), ...
	'RSC_slide_intensity', sim_params(6));
nuc_sum3 = run_simulation_from_genome(seq,'report',0, ...
	'poly_rate',sim_params(1), ...
	'REB1_a_rate', sim_params(2), 'REB1_e_rate', (sim_params(2)/2), ...
	'ABF1_a_rate', sim_params(2), 'ABF1_e_rate', (sim_params(2)/2), ...
	'RAP1_a_rate', sim_params(2), 'RAP1_e_rate', (sim_params(2)/2), ...
	'TF_evic_intensity', sim_params(3), ...
	'RSC_evic_length', sim_params(4), 'RSC_slide_length', sim_params(4).*2, ...
    'RSC_evic_intensity', sim_params(5), ...
	'RSC_slide_intensity', sim_params(6));
nuc_sum4 = run_simulation_from_genome(seq,'report',0, ...
	'poly_rate',sim_params(1), ...
	'REB1_a_rate', sim_params(2), 'REB1_e_rate', (sim_params(2)/2), ...
	'ABF1_a_rate', sim_params(2), 'ABF1_e_rate', (sim_params(2)/2), ...
	'RAP1_a_rate', sim_params(2), 'RAP1_e_rate', (sim_params(2)/2), ...
	'TF_evic_intensity', sim_params(3), ...
	'RSC_evic_length', sim_params(4), 'RSC_slide_length', sim_params(4).*2, ...
    'RSC_evic_intensity', sim_params(5), ...
	'RSC_slide_intensity', sim_params(6));
nuc_sum5 = run_simulation_from_genome(seq,'report',0, ...
	'poly_rate',sim_params(1), ...
	'REB1_a_rate', sim_params(2), 'REB1_e_rate', (sim_params(2)/2), ...
	'ABF1_a_rate', sim_params(2), 'ABF1_e_rate', (sim_params(2)/2), ...
	'RAP1_a_rate', sim_params(2), 'RAP1_e_rate', (sim_params(2)/2), ...
	'TF_evic_intensity', sim_params(3), ...
	'RSC_evic_length', sim_params(4), 'RSC_slide_length', sim_params(4).*2, ...
    'RSC_evic_intensity', sim_params(5), ...
	'RSC_slide_intensity', sim_params(6));
    
% get the feature of the simulation:
nuc_sum = nuc_sum1  + nuc_sum2 + nuc_sum3 + nuc_sum4 + nuc_sum5;
feature = Compare_Sum_To_Data(nuc_sum(700:1100), wt_data(700:1100));
		
% save the data to a .mat file:
disp('saving...')
save(['/cs/bd/Daniel/simulations/output/sim_' num2str(params_index) 'gene_' num2str(gene_index) '.mat'] , ...
	'nuc_sum', 'feature');
disp('saved...')