function full_cluster_sim( params_index , gene_index, sequences_structure, wt_3h)

NFR_pos = [601:1200];

% load all the necessary data:
addpath(genpath('/cs/bd/Daniel/nflab_scripts'));
addpath(genpath('/cs/bd/Daniel/nuc_simulator'));
seq = sequences_structure(gene_index,:);
wt_data = wt_3h(gene_index,:); 

if (isnan(wt_data(1)))
    nuc_sum = 0;
    likelihood = 0;
    plus1_dist = 0;
    minus1_dist = 0;

else
    
    % create the full parameter matrix
    create_full_params;

    % choose this specific sim parameters:
    sim_params = params(: , params_index);

    % the combvec params:
    % combvec(poly_rates, tf_rates, tf_evic_eff, rsc_length, rsc_evic, rsc_slide)

    % create five simulations that will be combined:
    nuc_sum1 = run_simulation_from_genome(seq,'report',0, ...
        'poly_rate',sim_params(1), ...
        'REB1_a_rate', sim_params(2), 'REB1_e_rate', (sim_params(2)/2), ...
        'ABF1_a_rate', sim_params(2), 'ABF1_e_rate', (sim_params(2)/2), ...
        'RAP1_a_rate', sim_params(2), 'RAP1_e_rate', (sim_params(2)/2), ...
        'TF_evic_intensity', sim_params(3), ...
        'RSC_evic_length', sim_params(4), 'RSC_slide_length', sim_params(4).*2, ...
        'RSC_evic_intensity', sim_params(5), ...
        'RSC_slide_intensity', sim_params(6));
    nuc_sum2 = run_simulation_from_genome(seq,'report',0, ...
        'poly_rate',sim_params(1), ...
        'REB1_a_rate', sim_params(2), 'REB1_e_rate', (sim_params(2)/2), ...
        'ABF1_a_rate', sim_params(2), 'ABF1_e_rate', (sim_params(2)/2), ...
        'RAP1_a_rate', sim_params(2), 'RAP1_e_rate', (sim_params(2)/2), ...
        'TF_evic_intensity', sim_params(3), ...
        'RSC_evic_length', sim_params(4), 'RSC_slide_length', sim_params(4).*2, ...
        'RSC_evic_intensity', sim_params(5), ...
        'RSC_slide_intensity', sim_params(6));
    nuc_sum3 = run_simulation_from_genome(seq,'report',0, ...
        'poly_rate',sim_params(1), ...
        'REB1_a_rate', sim_params(2), 'REB1_e_rate', (sim_params(2)/2), ...
        'ABF1_a_rate', sim_params(2), 'ABF1_e_rate', (sim_params(2)/2), ...
        'RAP1_a_rate', sim_params(2), 'RAP1_e_rate', (sim_params(2)/2), ...
        'TF_evic_intensity', sim_params(3), ...
        'RSC_evic_length', sim_params(4), 'RSC_slide_length', sim_params(4).*2, ...
        'RSC_evic_intensity', sim_params(5), ...
        'RSC_slide_intensity', sim_params(6));

    % get the feature of the simulation:
    nuc_sum = nuc_sum1 + nuc_sum2 + nuc_sum3;
    [likelihood, plus1_dist, minus1_dist] = ...
        Compare_Sum_To_Data(nuc_sum(1:2501), wt_data, NFR_pos, true);

end

% save the data to a .mat file:
save(['/cs/bd/Daniel/simulations/full_output/sim_' num2str(params_index) 'gene_' num2str(gene_index) '.mat'] , ...
	'nuc_sum', 'likelihood', 'plus1_dist', 'minus1_dist');