
params = struct('report', nan, ...
                  'n_steps', 25000,...
                  'gen_len', 3500,...
				  'nuc_width', 147, ...
                  'REB1_width', 10, ...
				  'ABF1_width', 14, ...
				  'RAP1_width', 15, ...
				  'slide_len', 5, ...
                  'linker_len', 10, ...
                  'poly_rate', 0, ...
				  'poly_pos', 1100:2500, ...
                  'REB1_a_rate', 0, ...
                  'REB1_e_rate', 0, ...
                  'ABF1_a_rate', 0, ...
                  'ABF1_e_rate', 0, ...
                  'RAP1_a_rate', 0, ...
                  'RAP1_e_rate', 0, ...
                  'nuc_base_a_rate', 0, ...
                  'nuc_base_e_rate', 0, ...
                  'nuc_base_r_rate', 0.1, ...
                  'nuc_base_l_rate', 0.1, ...
                  'TF_evic_intensity', 0, ...
                  'RSC_evic_intensity', 0, ...
                  'RSC_evic_length', 0, ...
                  'RSC_slide_intensity', 0, ...
                  'RSC_slide_length', 0, ...
                  'nuc_a_rate', 0*ones(1,3500), ...
                  'nuc_e_rate', 0*ones(1,3500), ...
                  'nuc_r_rate', 0.1*ones(1,3500), ...
                  'nuc_l_rate', 0.1*ones(1,3500));

s0 = zeros(1,3500);
s0(1750) = 1;
s0(1500) = 1;

[nuc_sum, time, nuc_s_hist, REB1_s_hist, ABF1_s_hist, RAP1_s_hist] = ...
        Simulate(params, 'n_steps', params.n_steps, 's0', s0, 'report', params.report);
    
plot(nuc_sum)